[build]
publish = "public"
command = "make production-build"

[build.environment]
HUGO_VERSION = "0.63.2"

[context.deploy-preview]
command = "make preview-build"

[context.branch-deploy]
command = "make preview-build"

[[redirects]]
from = "/spec:*"
to = "/spec/:splat"

[[redirects]]
from = "/spec/:rfcno/:shortname"
to = "/spec/:rfcno
